cd Z:\Projects\dide-runner
dub build
dide-runner.exe eyJkZXBlbmRlbmNpZXMiOnsidml2YSI6IioifSwiZW50cnkiOiJtYWluLmQiLCJmaWxlcyI6W3siY29udGVudCI6ImltcG9ydCB2aXZhLmlvO3ZvaWQgbWFpbigpIHsgcHJpbnRsbihcIkhlbGxvLCBXb3JsZCFcIik7IH0iLCJuYW1lIjoibWFpbi5kIn1dLCJsYW5ndWFnZSI6ImQiLCJvcHRpb25zIjpbXX0=